# -*- coding: utf-8 -*-
"""Courbetaux.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5rNXgZ72_wYuMvEzWPXW27d7hGoD0xg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

import pandas as pd

df = pd.read_excel(
    "courbe_zero_coupon.xlsx",
    sheet_name="Données",
    skiprows=2
)

# garder les 2 bonnes colonnes
df = df.iloc[:, :2].copy()
df.columns = ["maturite", "taux"]

# convertir les 2 colonnes en numérique
df["maturite"] = pd.to_numeric(df["maturite"], errors="coerce")
df["taux"] = pd.to_numeric(df["taux"], errors="coerce")

# supprimer les lignes invalides
df = df.dropna(subset=["maturite", "taux"]).reset_index(drop=True)

plt.figure(figsize=(8,5))
plt.plot(df["maturite"], df["taux"])

plt.title("Courbe des taux zéro-coupon - Banque de France")
plt.xlabel("Maturité (années)")
plt.ylabel("Taux (%)")
plt.grid(True)

plt.show()